// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3uJmT4LQDo6Pu6qnuSfx0Nnge185wLA',
    appId: '1:366147980597:web:7f784f955ea2ed5ccc907c',
    messagingSenderId: '366147980597',
    projectId: 'report-portal-13b31',
    authDomain: 'report-portal-13b31.firebaseapp.com',
    storageBucket: 'report-portal-13b31.firebasestorage.app',
    measurementId: 'G-DNE2QTLE0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5h5Fm_f6be6EpQ23A1oRVsIppgNxErOI',
    appId: '1:366147980597:android:ff457369e932bda2cc907c',
    messagingSenderId: '366147980597',
    projectId: 'report-portal-13b31',
    storageBucket: 'report-portal-13b31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABXt3SbDu4qF82EFM5wrisOrafPCF1N9s',
    appId: '1:366147980597:ios:4b78dafe28f1201bcc907c',
    messagingSenderId: '366147980597',
    projectId: 'report-portal-13b31',
    storageBucket: 'report-portal-13b31.firebasestorage.app',
    iosBundleId: 'com.example.reportPortalBoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABXt3SbDu4qF82EFM5wrisOrafPCF1N9s',
    appId: '1:366147980597:ios:4b78dafe28f1201bcc907c',
    messagingSenderId: '366147980597',
    projectId: 'report-portal-13b31',
    storageBucket: 'report-portal-13b31.firebasestorage.app',
    iosBundleId: 'com.example.reportPortalBoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN3uJmT4LQDo6Pu6qnuSfx0Nnge185wLA',
    appId: '1:366147980597:web:cc7f251762d67270cc907c',
    messagingSenderId: '366147980597',
    projectId: 'report-portal-13b31',
    authDomain: 'report-portal-13b31.firebaseapp.com',
    storageBucket: 'report-portal-13b31.firebasestorage.app',
    measurementId: 'G-13EVYCTJHP',
  );
}
